/**
 * 멤버십 더미 데이터
 */
import { Membership, MembershipBenefit, MembershipTier } from '@/lib/types/my-account';

export const mockMemberships: Membership[] = [
  {
    membershipId: 1,
    userId: 1,
    membershipTier: MembershipTier.DEEP_CHILL,
    points: 32450,
    totalStays: 12,
    totalSpending: 5680000,
    membershipNumber: 'CH-38291',
    memberSince: '2023-05-15',
    nextTierThreshold: 50000,
    pointsToNextTier: 17550,
    tierProgress: 65,
    nextTier: MembershipTier.DEEP_CHILL,
    expiringPoints: 5000,
    expirationDate: '2025-06-30',
    lastActivity: '2025-03-10',
  },
  {
    membershipId: 2,
    userId: 2,
    membershipTier: MembershipTier.CHILL_FLOW,
    points: 18750,
    totalStays: 4,
    totalSpending: 2340000,
    membershipNumber: 'CH-45672',
    memberSince: '2023-06-20',
    nextTierThreshold: 30000,
    pointsToNextTier: 11250,
    tierProgress: 42,
    nextTier: MembershipTier.DEEP_CHILL,
    expiringPoints: 2000,
    expirationDate: '2025-08-15',
    lastActivity: '2025-02-15',
  },
  {
    membershipId: 3,
    userId: 3,
    membershipTier: MembershipTier.CHILL_BREEZE,
    points: 5200,
    totalStays: 1,
    totalSpending: 520000,
    membershipNumber: 'CH-56789',
    memberSince: '2023-07-05',
    nextTierThreshold: 10000,
    pointsToNextTier: 4800,
    tierProgress: 52,
    nextTier: MembershipTier.CHILL_FLOW,
    expiringPoints: 0,
    expirationDate: '2025-07-05',
    lastActivity: '2025-01-20',
  },
];

export const mockMembershipBenefits: Record<MembershipTier, MembershipBenefit[]> = {
  [MembershipTier.CHILL_BREEZE]: [
    {
      benefitId: 1,
      membershipTier: MembershipTier.CHILL_BREEZE,
      benefitType: 'ROOM',
      discountPercentage: 5,
      description: '객실 요금 5% 할인',
    },
    {
      benefitId: 2,
      membershipTier: MembershipTier.CHILL_BREEZE,
      benefitType: 'GIFT_SHOP',
      discountPercentage: 5,
      description: '기프트샵 5% 할인',
    },
    {
      benefitId: 3,
      membershipTier: MembershipTier.CHILL_BREEZE,
      benefitType: 'WELCOME',
      discountPercentage: 0,
      description: '웰컴 드링크 제공',
    },
    {
      benefitId: 4,
      membershipTier: MembershipTier.CHILL_BREEZE,
      benefitType: 'BIRTHDAY',
      discountPercentage: 0,
      description: '생일 특별 혜택 (웰컴 디저트)',
    },
    {
      benefitId: 5,
      membershipTier: MembershipTier.CHILL_BREEZE,
      benefitType: 'POINTS',
      discountPercentage: 0,
      description: '객실 1박당 Chill 포인트 100점 적립',
    },
  ],
  [MembershipTier.CHILL_FLOW]: [
    {
      benefitId: 6,
      membershipTier: MembershipTier.CHILL_FLOW,
      benefitType: 'ROOM',
      discountPercentage: 10,
      description: '객실 요금 10% 할인',
    },
    {
      benefitId: 7,
      membershipTier: MembershipTier.CHILL_FLOW,
      benefitType: 'DINING',
      discountPercentage: 5,
      description: '다이닝 이용 금액 5% 할인',
    },
    {
      benefitId: 8,
      membershipTier: MembershipTier.CHILL_FLOW,
      benefitType: 'SPA',
      discountPercentage: 10,
      description: '스파 트리트먼트 10% 할인',
    },
    {
      benefitId: 9,
      membershipTier: MembershipTier.CHILL_FLOW,
      benefitType: 'GIFT_SHOP',
      discountPercentage: 10,
      description: '기프트샵 10% 할인',
    },
    {
      benefitId: 10,
      membershipTier: MembershipTier.CHILL_FLOW,
      benefitType: 'CHECKOUT',
      discountPercentage: 0,
      description: '레이트 체크아웃 (오후 2시까지, 가능 시)',
    },
    {
      benefitId: 11,
      membershipTier: MembershipTier.CHILL_FLOW,
      benefitType: 'ROOM_UPGRADE',
      discountPercentage: 0,
      description: '룸 업그레이드 1회 (가능 시, 연간)',
    },
    {
      benefitId: 12,
      membershipTier: MembershipTier.CHILL_FLOW,
      benefitType: 'POINTS',
      discountPercentage: 0,
      description: '객실 1박당 Chill 포인트 200점 적립',
    },
  ],
  [MembershipTier.DEEP_CHILL]: [
    {
      benefitId: 13,
      membershipTier: MembershipTier.DEEP_CHILL,
      benefitType: 'ROOM',
      discountPercentage: 15,
      description: '객실 요금 15% 할인',
    },
    {
      benefitId: 14,
      membershipTier: MembershipTier.DEEP_CHILL,
      benefitType: 'DINING',
      discountPercentage: 10,
      description: '다이닝 이용 금액 10% 할인',
    },
    {
      benefitId: 15,
      membershipTier: MembershipTier.DEEP_CHILL,
      benefitType: 'SPA',
      discountPercentage: 20,
      description: '스파 트리트먼트 20% 할인',
    },
    {
      benefitId: 16,
      membershipTier: MembershipTier.DEEP_CHILL,
      benefitType: 'GIFT_SHOP',
      discountPercentage: 15,
      description: '기프트샵 15% 할인',
    },
    {
      benefitId: 17,
      membershipTier: MembershipTier.DEEP_CHILL,
      benefitType: 'CHECKIN',
      discountPercentage: 0,
      description: '얼리 체크인 (오전 11시부터)/레이트 체크아웃 (오후 4시까지)',
    },
    {
      benefitId: 18,
      membershipTier: MembershipTier.DEEP_CHILL,
      benefitType: 'VIP',
      discountPercentage: 0,
      description: 'VIP 컨시어지 서비스',
    },
    {
      benefitId: 19,
      membershipTier: MembershipTier.DEEP_CHILL,
      benefitType: 'EVENTS',
      discountPercentage: 0,
      description: '멤버 전용 이벤트 초대',
    },
    {
      benefitId: 20,
      membershipTier: MembershipTier.DEEP_CHILL,
      benefitType: 'CABANA',
      discountPercentage: 0,
      description: '프라이빗 카바나 2시간 무료 이용 (연간 1회)',
    },
    {
      benefitId: 21,
      membershipTier: MembershipTier.DEEP_CHILL,
      benefitType: 'RESERVATION',
      discountPercentage: 0,
      description: 'Chill Elegance 레스토랑 우선 예약권',
    },
    {
      benefitId: 22,
      membershipTier: MembershipTier.DEEP_CHILL,
      benefitType: 'SPECIAL_OCCASION',
      discountPercentage: 0,
      description: '특별 기념일 케이크 및 샴페인 서비스',
    },
    {
      benefitId: 23,
      membershipTier: MembershipTier.DEEP_CHILL,
      benefitType: 'POINTS',
      discountPercentage: 0,
      description: '객실 1박당 Chill 포인트 300점 적립',
    },
  ],
};

// 현재 로그인한 사용자의 멤버십 정보로 가정
export const currentMembership = mockMemberships[0];
