/**
 * 포인트 트랜잭션 더미 데이터
 */
import { PointTransaction, PointTransactionType } from '@/lib/types/my-account';

export const mockPointTransactions: PointTransaction[] = [
  {
    transactionId: 'trx-123456',
    userId: 1,
    points: 3000,
    referenceId: 1001,
    referenceType: 'ROOM_STAY',
    transactionType: PointTransactionType.EARNED,
    transactionDate: '2025-03-10T15:30:00Z',
    description: 'Room Stay - Chill Serenity Room',
  },
  {
    transactionId: 'trx-123455',
    userId: 1,
    points: 850,
    referenceId: 2001,
    referenceType: 'DINING',
    transactionType: PointTransactionType.EARNED,
    transactionDate: '2025-02-14T19:45:00Z',
    description: 'Dining - Chill Elegance',
  },
  {
    transactionId: 'trx-123454',
    userId: 1,
    points: 12000,
    referenceId: 1002,
    referenceType: 'ROOM_STAY',
    transactionType: PointTransactionType.EARNED,
    transactionDate: '2025-01-15T11:20:00Z',
    description: 'Room Stay - Chill Lake Suite',
  },
  {
    transactionId: 'trx-123453',
    userId: 1,
    points: 1200,
    referenceId: 3001,
    referenceType: 'SPA',
    transactionType: PointTransactionType.EARNED,
    transactionDate: '2025-01-12T14:15:00Z',
    description: 'Spa Treatment',
  },
  {
    transactionId: 'trx-123452',
    userId: 1,
    points: 450,
    referenceId: 4001,
    referenceType: 'GIFT_SHOP',
    transactionType: PointTransactionType.EARNED,
    transactionDate: '2024-12-10T16:30:00Z',
    description: 'Gift Shop Purchase',
  },
  {
    transactionId: 'trx-123451',
    userId: 1,
    points: -10000,
    referenceId: 5001,
    referenceType: 'ROOM_REDEMPTION',
    transactionType: PointTransactionType.REDEEMED,
    transactionDate: '2024-11-25T09:45:00Z',
    description: 'Room Charge Redemption',
  },
  {
    transactionId: 'trx-123450',
    userId: 1,
    points: 2000,
    referenceId: null,
    referenceType: 'SIGNUP_BONUS',
    transactionType: PointTransactionType.BONUS,
    transactionDate: '2023-05-15T09:00:00Z',
    description: 'Welcome Bonus',
  },
  {
    transactionId: 'trx-123449',
    userId: 1,
    points: 1000,
    referenceId: null,
    referenceType: 'BIRTHDAY_BONUS',
    transactionType: PointTransactionType.BONUS,
    transactionDate: '2024-09-20T00:00:00Z',
    description: 'Birthday Bonus',
  },
  {
    transactionId: 'trx-123448',
    userId: 1,
    points: -5000,
    referenceId: 6001,
    referenceType: 'SPA_REDEMPTION',
    transactionType: PointTransactionType.REDEEMED,
    transactionDate: '2024-08-15T13:20:00Z',
    description: 'Spa Treatment Redemption',
  },
  {
    transactionId: 'trx-123447',
    userId: 1,
    points: -2000,
    referenceId: 7001,
    referenceType: 'DINING_REDEMPTION',
    transactionType: PointTransactionType.REDEEMED,
    transactionDate: '2024-07-05T19:30:00Z',
    description: 'Dining Charge Redemption',
  },
];

// 현재 로그인한 사용자의 포인트 트랜잭션
export const currentUserPointTransactions = mockPointTransactions;
