spring:
  application:
    name: back-end
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/chill?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# JWT 설정
custom:
  jwt:
    secretKey: c2lzdC1ob3RlbC1wcm9qZWN0LWp3dC1zZWNyZXQta2V5LWZvci1zZWN1cmUtYXV0aGVudGljYXRpb24=
    access-token-validity-in-seconds: 3600
    refresh-token-validity-in-seconds: 86400

# 로깅 설정
logging:
  level:
    com.hotel.hotelproject: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
