spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chill?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # 데이터베이스 URL
    username: chill # 데이터베이스 사용자명
    password: 1111 # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver # JDBC 드라이버
  jpa:
    database: mysql # 사용할 데이터베이스 종류
    database-platform: org.hibernate.dialect.MySQL8Dialect # Hibernate 방언 설정

# 개발 환경 설정
---
spring:
  config:
    activate:
      on-profile: dev # 'dev' 프로파일 활성화 시 적용
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_chill_dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # 개발 DB URL
  jpa:
    hibernate:
      ddl-auto: update # 개발 환경에서는 스키마 자동 업데이트

# 테스트 환경 설정
---
spring:
  config:
    activate:
      on-profile: test # 'test' 프로파일 활성화 시 적용
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_chill_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # 테스트 DB URL
  jpa:
    hibernate:
      ddl-auto: create-drop # 테스트 환경에서는 매번 스키마 재생성
